name: becca_inventory
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  formz: ^0.6.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.0.0
  intl: ^0.18.1

dev_dependencies:
  build_runner: 2.4.6
  flutter_gen_runner: 5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/images/
    - assets/icons/
